### ISSUE TITLE
Define and Document Developer Workflows

### ISSUE THREAD

**Issue by thescientist13** [NewportDataProject/data-night#2]
### Overview
Providing reproducible development environments is a good convention practiced in most (good) development shops.  In particular it is super valuable when it comes to onboarding and for collaboration / support (same versions, same tools, same knowledge base).

However, generally these come with a base expectation of skill sets, in particular familiarity with the command line.  For data night, we want anyone with an interest or desire to be able to participate, so to do we, we need to provided and define options, while still focusing around a base stack / common core.

### Objectives
Our goal is to support contributors of different skill sets and with different interests.  

Tasks we want to support:
- Data Gathering / Ingestion
- Data Analysis
- Visualizing / Processing Data
- Displaying / rendering data (in a GUI)

Users we want to support:
- Not familiar with the command line / programming, but is interested in analyzing or gathering data
- Proficient in programming languages (Python primarily)
- Interested in product developmnet

### Proposal

These are the three workflows that will be supported:
1.  _Centralized (Jupyter Hub)_ - Anyone can login, play around with scripts and collaborate on existing scripts.  No need to install anything locally. see https://github.com/davenamin/jupyterhub_dokku_example
1.  _Localized Containerized (Docker)_ - Get a pre-packaged environment with all the tools and common packages (like Python, Conda, local Jupyter Notebook server) and interact with it on your own machine via CLI.  Container would mount a local drive / directory to ensure all user generated data persists.
1.  _Localized Bare Metal_ - list of the packages and tools, that can then be manually installed by any user

This is the stack to propose
- Ubuntu
- Python 3
- Conda
- Jupyter
- nginx

**Comment by thescientist13** [comment]
@paulopperman 
Not sure if you see any of this fitting in the README, or maybe in the wiki as an expanded version of what is being documented in the README?  

Let me know your thoughts in general and how you best think of sharing this content (assuming it's useful / helpful to have 😊  ).  

Happy to put it wherever in time for data night

**Comment by paulopperman** [comment]
I think I partially cover the conceptual part in PR #7 , although not everything is explicit.

**Comment by thescientist13** [comment]
@paulopperman 
I added some of the content here as part of PR #8 (issue #5 ).  

Looks like between both of our PRs we may have most of it covered, though as you say, not as explicitly as here (which I think is fine)

**Comment by paulopperman** [comment]
closed by #16 and #8
